package org.game.mockData;

import org.game.gui.Coordinates;
import org.game.gui.MapCell;
import org.game.gui.MapCellType;

import java.util.ArrayList;

public class StandardMap {
    public static final ArrayList<MapCell> MAP = generateMap();

    private static ArrayList<MapCell> generateMap() {
        ArrayList<Coordinates> land = new ArrayList<>() {
            {
                add(new Coordinates(0,21));
                add(new Coordinates(0,22));
                add(new Coordinates(0,23));
                add(new Coordinates(0,24));
                add(new Coordinates(0,25));
                add(new Coordinates(0,26));
                add(new Coordinates(0,27));
                add(new Coordinates(0,28));
                add(new Coordinates(0,29));
                add(new Coordinates(0,30));
                add(new Coordinates(0,31));
                add(new Coordinates(1,28));
                add(new Coordinates(1,29));
                add(new Coordinates(1,30));
                add(new Coordinates(1,31));
                add(new Coordinates(2,7));
                add(new Coordinates(2,8));
                add(new Coordinates(2,31));
                add(new Coordinates(3,0));
                add(new Coordinates(3,6));
                add(new Coordinates(3,7));
                add(new Coordinates(3,8));
                add(new Coordinates(3,9));
                add(new Coordinates(4,0));
                add(new Coordinates(4,7));
                add(new Coordinates(4,8));
                add(new Coordinates(4,22));
                add(new Coordinates(4,23));
                add(new Coordinates(4,24));
                add(new Coordinates(5,21));
                add(new Coordinates(5,22));
                add(new Coordinates(5,23));
                add(new Coordinates(5,24));
                add(new Coordinates(5,31));
                add(new Coordinates(6,12));
                add(new Coordinates(6,13));
                add(new Coordinates(6,21));
                add(new Coordinates(6,22));
                add(new Coordinates(6,23));
                add(new Coordinates(6,24));
                add(new Coordinates(6,30));
                add(new Coordinates(6,31));
                add(new Coordinates(7,12));
                add(new Coordinates(7,13));
                add(new Coordinates(7,14));
                add(new Coordinates(7,15));
                add(new Coordinates(7,23));
                add(new Coordinates(7,24));
                add(new Coordinates(7,29));
                add(new Coordinates(7,30));
                add(new Coordinates(7,31));
                add(new Coordinates(8,10));
                add(new Coordinates(8,11));
                add(new Coordinates(8,12));
                add(new Coordinates(8,13));
                add(new Coordinates(8,14));
                add(new Coordinates(8,15));
                add(new Coordinates(8,29));
                add(new Coordinates(8,30));
                add(new Coordinates(8,31));
                add(new Coordinates(9,7));
                add(new Coordinates(9,8));
                add(new Coordinates(9,9));
                add(new Coordinates(9,10));
                add(new Coordinates(9,11));
                add(new Coordinates(9,12));
                add(new Coordinates(9,13));
                add(new Coordinates(9,28));
                add(new Coordinates(9,29));
                add(new Coordinates(9,30));
                add(new Coordinates(9,31));
                add(new Coordinates(10,6));
                add(new Coordinates(10,7));
                add(new Coordinates(10,8));
                add(new Coordinates(10,9));
                add(new Coordinates(10,10));
                add(new Coordinates(10,11));
                add(new Coordinates(10,28));
                add(new Coordinates(10,29));
                add(new Coordinates(10,30));
                add(new Coordinates(10,31));
                add(new Coordinates(11,5));
                add(new Coordinates(11,6));
                add(new Coordinates(11,7));
                add(new Coordinates(11,8));
                add(new Coordinates(11,9));
                add(new Coordinates(11,10));
                add(new Coordinates(11,30));
                add(new Coordinates(11,31));
                add(new Coordinates(12,7));
                add(new Coordinates(12,8));
                add(new Coordinates(12,31));
                add(new Coordinates(15,13));
                add(new Coordinates(15,14));
                add(new Coordinates(15,23));
                add(new Coordinates(15,24));
                add(new Coordinates(15,25));
                add(new Coordinates(15,26));
                add(new Coordinates(15,27));
                add(new Coordinates(16,13));
                add(new Coordinates(16,14));
                add(new Coordinates(16,24));
                add(new Coordinates(16,25));
                add(new Coordinates(16,26));
                add(new Coordinates(16,27));
                add(new Coordinates(17,12));
                add(new Coordinates(17,13));
                add(new Coordinates(17,26));
                add(new Coordinates(17,27));
                add(new Coordinates(18,10));
                add(new Coordinates(18,11));
                add(new Coordinates(18,12));
                add(new Coordinates(18,13));
                add(new Coordinates(18,26));
                add(new Coordinates(18,27));
                add(new Coordinates(18,28));
                add(new Coordinates(18,29));
                add(new Coordinates(19,10));
                add(new Coordinates(19,11));
                add(new Coordinates(20,10));
                add(new Coordinates(20,11));
                add(new Coordinates(21,8));
                add(new Coordinates(21,9));
                add(new Coordinates(21,10));
                add(new Coordinates(21,11));
                add(new Coordinates(22,3));
                add(new Coordinates(23,2));
                add(new Coordinates(23,3));
                add(new Coordinates(23,4));
                add(new Coordinates(23,5));
                add(new Coordinates(23,5));
                add(new Coordinates(23,25));
                add(new Coordinates(23,26));
                add(new Coordinates(23,27));
                add(new Coordinates(24,1));
                add(new Coordinates(24,2));
                add(new Coordinates(24,3));
                add(new Coordinates(24,4));
                add(new Coordinates(24,5));
                add(new Coordinates(24,16));
                add(new Coordinates(24,25));
                add(new Coordinates(24,26));
                add(new Coordinates(24,27));
                add(new Coordinates(24,28));
                add(new Coordinates(24,29));
                add(new Coordinates(25,1));
                add(new Coordinates(25,2));
                add(new Coordinates(25,3));
                add(new Coordinates(25,4));
                add(new Coordinates(25,5));
                add(new Coordinates(25,14));
                add(new Coordinates(25,15));
                add(new Coordinates(25,16));
                add(new Coordinates(25,17));
                add(new Coordinates(25,26));
                add(new Coordinates(25,27));
                add(new Coordinates(25,28));
                add(new Coordinates(25,29));
                add(new Coordinates(25,30));
                add(new Coordinates(26,1));
                add(new Coordinates(26,2));
                add(new Coordinates(26,3));
                add(new Coordinates(26,4));
                add(new Coordinates(26,5));
                add(new Coordinates(26,12));
                add(new Coordinates(26,13));
                add(new Coordinates(26,14));
                add(new Coordinates(26,15));
                add(new Coordinates(26,16));
                add(new Coordinates(26,17));
                add(new Coordinates(26,26));
                add(new Coordinates(26,27));
                add(new Coordinates(26,28));
                add(new Coordinates(26,29));
                add(new Coordinates(26,30));
                add(new Coordinates(27,2));
                add(new Coordinates(27,3));
                add(new Coordinates(27,4));
                add(new Coordinates(27,5));
                add(new Coordinates(27,6));
                add(new Coordinates(27,14));
                add(new Coordinates(27,15));
                add(new Coordinates(27,16));
                add(new Coordinates(27,28));
                add(new Coordinates(27,29));
                add(new Coordinates(28,4));
                add(new Coordinates(28,5));
                add(new Coordinates(28,14));
                add(new Coordinates(28,28));
                add(new Coordinates(28,29));
                add(new Coordinates(30,19));
                add(new Coordinates(30,20));
                add(new Coordinates(31,18));
                add(new Coordinates(31,19));
                add(new Coordinates(31,20));
                add(new Coordinates(31,21));
                add(new Coordinates(31,22));
                add(new Coordinates(32,12));
                add(new Coordinates(32,13));
                add(new Coordinates(32,20));
                add(new Coordinates(32,21));
                add(new Coordinates(32,22));
                add(new Coordinates(32,23));
                add(new Coordinates(33,3));
                add(new Coordinates(33,4));
                add(new Coordinates(33,5));
                add(new Coordinates(33,6));
                add(new Coordinates(33,7));
                add(new Coordinates(33,8));
                add(new Coordinates(33,9));
                add(new Coordinates(33,10));
                add(new Coordinates(33,11));
                add(new Coordinates(33,12));
                add(new Coordinates(33,13));
                add(new Coordinates(33,14));
                add(new Coordinates(33,15));
                add(new Coordinates(33,22));
                add(new Coordinates(33,23));
               /* add(new Coordinates(0, 0));
                add(new Coordinates(1, 0));
                add(new Coordinates(2, 0));
                add(new Coordinates(3, 0));
                add(new Coordinates(4, 0));
                add(new Coordinates(5, 0));
                add(new Coordinates(9, 0));
                add(new Coordinates(10, 0));
                add(new Coordinates(11, 0));
                add(new Coordinates(17, 0));
                add(new Coordinates(18, 0));
                add(new Coordinates(19, 0));
                add(new Coordinates(20, 0));
                add(new Coordinates(21, 0));
                add(new Coordinates(22, 0));
                add(new Coordinates(23, 0));
                add(new Coordinates(24, 0));
                add(new Coordinates(25, 0));
                add(new Coordinates(26, 0));
                add(new Coordinates(27, 0));
                add(new Coordinates(0, 1));
                add(new Coordinates(1, 1));
                add(new Coordinates(2, 1));
                add(new Coordinates(5, 1));
                add(new Coordinates(9, 1));
                add(new Coordinates(10, 1));
                add(new Coordinates(11, 1));
                add(new Coordinates(12, 1));
                add(new Coordinates(21, 1));
                add(new Coordinates(25, 1));
                add(new Coordinates(29, 1));
                add(new Coordinates(0, 2));
                add(new Coordinates(8, 2));
                add(new Coordinates(9, 2));
                add(new Coordinates(10, 2));
                add(new Coordinates(29, 2));
                add(new Coordinates(27, 3));
                add(new Coordinates(28, 3));
                add(new Coordinates(29, 3));
                add(new Coordinates(0, 4));
                add(new Coordinates(28, 4));
                add(new Coordinates(29, 4));
                add(new Coordinates(0, 5));
                add(new Coordinates(22, 5));
                add(new Coordinates(22, 6));
                add(new Coordinates(23, 6));
                add(new Coordinates(9, 7));
                add(new Coordinates(10, 7));
                add(new Coordinates(11, 7));
                add(new Coordinates(12, 7));
                add(new Coordinates(20, 7));
                add(new Coordinates(21, 7));
                add(new Coordinates(22, 7));
                add(new Coordinates(23, 7));
                add(new Coordinates(24, 7));
                add(new Coordinates(6, 8));
                add(new Coordinates(7, 8));
                add(new Coordinates(8, 8));
                add(new Coordinates(9, 8));
                add(new Coordinates(10, 8));
                add(new Coordinates(11, 8));
                add(new Coordinates(20, 8));
                add(new Coordinates(21, 8));
                add(new Coordinates(22, 8));
                add(new Coordinates(23, 8));
                add(new Coordinates(24, 8));
                add(new Coordinates(28, 8));
                add(new Coordinates(29, 8));
                add(new Coordinates(6, 9));
                add(new Coordinates(7, 9));
                add(new Coordinates(8, 9));
                add(new Coordinates(9, 9));
                add(new Coordinates(10, 9));
                add(new Coordinates(21, 9));
                add(new Coordinates(22, 9));
                add(new Coordinates(23, 9));
                add(new Coordinates(24, 9));
                add(new Coordinates(27, 9));
                add(new Coordinates(28, 9));
                add(new Coordinates(29, 9));
                add(new Coordinates(6, 10));
                add(new Coordinates(7, 10));
                add(new Coordinates(8, 10));
                add(new Coordinates(9, 10));
                add(new Coordinates(10, 10));
                add(new Coordinates(22, 10));
                add(new Coordinates(28, 10));
                add(new Coordinates(5, 11));
                add(new Coordinates(6, 11));
                add(new Coordinates(7, 11));
                add(new Coordinates(8, 11));
                add(new Coordinates(10, 11));
                add(new Coordinates(3, 12));
                add(new Coordinates(4, 12));
                add(new Coordinates(5, 12));
                add(new Coordinates(6, 12));
                add(new Coordinates(7, 12));
                add(new Coordinates(8, 12));
                add(new Coordinates(7, 13));
                add(new Coordinates(7, 14));
                add(new Coordinates(28, 14));
                add(new Coordinates(29, 14));
                add(new Coordinates(30, 14));
                add(new Coordinates(7, 15));
                add(new Coordinates(8, 15));
                add(new Coordinates(21, 15));
                add(new Coordinates(22, 15));
                add(new Coordinates(30, 15));
                add(new Coordinates(31, 15));
                add(new Coordinates(18, 16));
                add(new Coordinates(19, 16));
                add(new Coordinates(20, 16));
                add(new Coordinates(21, 16));
                add(new Coordinates(22, 16));
                add(new Coordinates(23, 16));
                add(new Coordinates(30, 16));
                add(new Coordinates(31, 16));
                add(new Coordinates(19, 17));
                add(new Coordinates(20, 17));
                add(new Coordinates(21, 17));
                add(new Coordinates(22, 17));
                add(new Coordinates(31, 17));
                add(new Coordinates(11, 18));
                add(new Coordinates(19, 18));
                add(new Coordinates(20, 18));
                add(new Coordinates(21, 18));
                add(new Coordinates(22, 18));
                add(new Coordinates(1, 19));
                add(new Coordinates(2, 19));
                add(new Coordinates(10, 19));
                add(new Coordinates(11, 19));
                add(new Coordinates(12, 19));
                add(new Coordinates(19, 19));
                add(new Coordinates(0, 20));
                add(new Coordinates(1, 20));
                add(new Coordinates(2, 20));
                add(new Coordinates(7, 20));
                add(new Coordinates(8, 20));
                add(new Coordinates(9, 20));
                add(new Coordinates(10, 20));
                add(new Coordinates(11, 20));
                add(new Coordinates(31, 20));
                add(new Coordinates(0, 21));
                add(new Coordinates(1, 21));
                add(new Coordinates(2, 21));
                add(new Coordinates(26, 21));
                add(new Coordinates(30, 21));
                add(new Coordinates(31, 21));
                add(new Coordinates(0, 22));
                add(new Coordinates(1, 22));
                add(new Coordinates(2, 22));
                add(new Coordinates(3, 22));
                add(new Coordinates(24, 22));
                add(new Coordinates(25, 22));
                add(new Coordinates(26, 22));
                add(new Coordinates(27, 22));
                add(new Coordinates(28, 22));
                add(new Coordinates(29, 22));
                add(new Coordinates(30, 22));
                add(new Coordinates(31, 22));*/
            }
        };
        ArrayList<MapCell> cells = new ArrayList<>();
        for (int x = 33; x >= 0; x--) {
            for (int y = 31; y >= 0; y--) {
                int finalX = x;
                int finalY = y;
                if (land.stream().anyMatch(coordinates -> coordinates.equals(new Coordinates(finalX, finalY)))) {
                    cells.add(new MapCell(new Coordinates(x, y), MapCellType.LAND));
                } else {
                    cells.add(new MapCell(new Coordinates(x, y), MapCellType.WATER));
                }
            }
        }
        return cells;
    }
}
